application setup

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -13,3 +13,10 @@ if [ ! $RC -eq 0 ]; then
   echo 'COMMIT ABORTED: Brakeman has detected one or more security vulnerabilities, please review them and re-commit your changes.'
   exit 1
 fi
+
+bundle exec rspec
+RC=$?
+if [ ! $RC -eq 0 ]; then
+  echo 'COMMIT ABORTED: rspec has detected one or more security vulnerabilities, please review them and re-commit your changes.'
+  exit 1
+fi
