optional mutant testing

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -21,10 +21,12 @@ if [ ! $RC -eq 0 ]; then
   exit 1
 fi
 
-mutant_classes="CredentialPair ContentBlock Api::ContentBlocksController"
-RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec `echo $mutant_classes`
-#RC=$?
-#if [ ! $RC -eq 0 ]; then
-#  echo 'COMMIT ABORTED: mutant has found mutations which let your tests still pass.'
-#  exit 1
-#fi
+if [ ! -z "$MUTANT" ]; then
+  mutant_classes="CredentialPair ContentBlock Api::ContentBlocksController"
+  RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec `echo $mutant_classes`
+  RC=$?
+  if [ ! $RC -eq 0 ]; then
+    echo 'COMMIT ABORTED: mutant has found mutations which let your tests still pass.'
+    exit 1
+  fi
+fi
